#!/usr/bin/perl -w

use strict;


open(FH, $ARGV[0]);

printf("!FORMAT=XDS_ASCII   MERGE=TRUE   FRIEDEL'S_LAW=TRUE\n");
printf("!SPACE_GROUP_NUMBER=18\n");
printf("!UNIT_CELL_CONSTANTS=  61.53 90.81 151.0  90.0 90.0 90.0\n");
printf("!NUMBER_OF_ITEMS_IN_EACH_DATA_RECORD=5\n");
printf("!X-RAY_WAVELENGTH= 1.04982\n");
printf("!ITEM_H=1\n");
printf("!ITEM_K=2\n");
printf("!ITEM_L=3\n");
printf("!ITEM_IOBS=4\n");
printf("!ITEM_SIGMA(IOBS)=5\n");
printf("!END_OF_HEADER\n");

my $line;
while ( $line = <FH> ) {

	chomp($line);

	if ( $line =~ /^\s+([0-9\-]+)\s+([0-9\-]+)\s+([0-9\-]+)\s+([0-9\.\-]+)\s+([\-]+)\s+([0-9\.\-]+)/ ) {

		my $h = $1;
		my $k = $2;
		my $l = $3;
		my $int = $4;
		my $sig = $6;  # Yes, it's meant to be $6 not $5 ($5 is phase)

#		printf("%6i %5i %5i % 8.3E % 8.3E     0.0     0.0     0.0 9999.00 1\n", $h, $k, $l, $int, $sig);
		printf("%6i %6i %5i %9.2f %9.2f\n", $h, $k, $l, $int, $sig);

	} else {

		printf(STDERR "Unrecognised: '%s'\n", $line);

	}

}

printf("!END_OF_DATA");

close(FH);
