#!/bin/bash

# Usage:
# for i in `ls test*stream`; do ./stdev $i; done > out-geom-ref.txt
# module load gnuplot/5.2.0
# gnuplot < plot.gp

echo $1 " " |  tr -dc '0-9' |tr -d '\n'
echo " " | tr -d '\n'
cat $1 | grep Cell | wc -l | tr -d '\n'
echo " " | tr -d '\n'
cat $1 | grep filename | wc -l | tr -d '\n'
echo " " | tr -d '\n'
cat $1 | grep Cell | awk '{sum+=$3} END {print sum/NR}' | tr -d '\n'
echo " " | tr -d '\n'
cat $1 | grep Cell | awk '{delta = $3 - avg; avg += delta / NR; mean2 += delta * ($3 - avg); } END { print sqrt(mean2 / (NR-1)); }'  | tr -d '\n'
echo " " | tr -d '\n'

cat $1 | grep Cell | awk '{sum+=$4} END {print sum/NR}' | tr -d '\n'
echo " " | tr -d '\n'
cat $1 | grep Cell | awk '{delta = $4 - avg; avg += delta / NR; mean2 += delta * ($4 - avg); } END { print sqrt(mean2 / (NR-1)); }'  | tr -d '\n'
echo " " | tr -d '\n'

cat $1 | grep Cell | awk '{sum+=$5} END {print sum/NR}' | tr -d '\n'
echo " " | tr -d '\n'
cat $1 | grep Cell | awk '{delta = $5 - avg; avg += delta / NR; mean2 += delta * ($5 - avg); } END { print sqrt(mean2 / (NR-1)); }'  
